name: Build and Publish

on:
  push:

env:
  IMAGE_NAME: mrn_status

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build . --tag $IMAGE_NAME

      - name: Push image to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

          IMAGE_ID=ghcr.io/${{ github.repository }}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=${{ github.sha }}

          docker tag $IMAGE_NAME $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:${{ github.sha }}
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
